"""Hold the scanner to a noise budget on real code it was not tuned against.

The labelled benchmark cannot catch the failure that actually kills a scanner:
rules that score perfectly on their own fixture and then fire forty times on a
real repository. This suite scans the third-party packages installed alongside
the project — real, published, reviewed code written by people who have never
seen these rules — and fails when the noise rate rises.

Budgets are set roughly double the measured rate, so tuning has room and a
genuine regression still trips them. The numbers behind them are regenerated by
`python src/evaluation/run_fp_eval.py`.
"""
from __future__ import annotations

import pytest

pytestmark = pytest.mark.quality

# The `noise` and `bandit_available` fixtures come from conftest.py; the scan is
# session-scoped because it costs the better part of a minute.

# A published package does not contain a live credential. Any hit here is the
# detector firing on documentation, a test fixture, or a hash — and a secret
# scanner that does that gets muted, which costs more than the miss it prevents.
MAX_SECRET_FALSE_POSITIVES = 0

# Code findings on real libraries are not adjudicated as false positives (real
# code does use subprocess and md5). They are capped as noise: beyond roughly
# one finding per thousand lines, nobody reads the report. Measured at 0.23/kLOC
# over 424 kLOC, down from 0.50 before the skip list was widened.
MAX_CODE_PER_KLOC = 0.6
MAX_HIGH_SEVERITY_PER_KLOC = 0.1


def test_corpus_actually_reaches_the_detectors(noise):
    # The scanner drops vendored paths, and the corpus comes from
    # `site-packages` — which is a vendor directory. If the re-rooting in the
    # harness ever breaks, every assertion below passes against an empty scan.
    assert noise.scanned_files >= noise.files * 0.95, (
        f"only {noise.scanned_files} of {noise.files} files reached the "
        "detectors — the corpus is being filtered, not scanned"
    )
    assert noise.kloc > 10, "corpus is too small to measure a rate against"


def test_no_secrets_are_found_in_published_packages(noise, bandit_available):
    assert len(noise.secret_findings) <= MAX_SECRET_FALSE_POSITIVES, (
        "the secret detector fired on real third-party code:\n  "
        + "\n  ".join(noise.secret_findings[:10])
    )


def test_code_noise_stays_within_budget(noise, bandit_available):
    if not bandit_available:
        pytest.skip("bandit is not installed in this environment")
    assert noise.code_per_kloc <= MAX_CODE_PER_KLOC, (
        f"{noise.code_findings} findings over {noise.kloc:.1f} kLOC "
        f"= {noise.code_per_kloc:.2f}/kLOC. Loudest rules: "
        f"{dict(sorted(noise.by_rule.items(), key=lambda kv: -kv[1])[:5])}"
    )


def test_high_severity_noise_stays_within_budget(noise, bandit_available):
    if not bandit_available:
        pytest.skip("bandit is not installed in this environment")
    # High severity is what `--fail-on high` blocks a build on, so this rate is
    # the one that decides whether the CI gate is usable.
    assert noise.high_per_kloc <= MAX_HIGH_SEVERITY_PER_KLOC, (
        f"{noise.high_severity} high-severity findings over "
        f"{noise.kloc:.1f} kLOC = {noise.high_per_kloc:.2f}/kLOC"
    )


def test_the_rules_known_to_be_pure_noise_stay_out(noise):
    """The skip list in `detectors/code.py` is load-bearing, not cosmetic.

    Each of these was measured on this corpus and removed for a stated reason:
    B4xx report an import rather than a call, B110/B112 report a swallowed
    exception, and B105-B107 duplicate the secret detector without its entropy
    gate. Together they were more than half of every finding produced. A bandit
    upgrade that renumbers or re-enables one would put the noise back silently.
    """
    banned = (
        {f"B4{n:02d}" for n in range(1, 16)}
        | {"B110", "B112"}
        | {"B105", "B106", "B107"}
    )
    noisy = {rule: n for rule, n in noise.by_rule.items() if rule in banned}
    assert not noisy, f"rules on the skip list are back in the output: {noisy}"
